### ISSUE TITLE
When will the code and pretrained model be released?

### ISSUE THREAD

**Issue by l11x0m7** [mingdachen/WikiTableT#1]
Hi, 
I wonder when  will the code and pretrained model released?

Thanks!

**Comment by mingdachen** [comment]
Hi @l11x0m7 , thanks for your interest! I am still working on cleaning up the codebase. Will release the code & models soon after the ACL deadline (Feb. 1st).

**Comment by l11x0m7** [comment]
Hi, 
Is the test infobox and wikidata included in "infobox.json" and "wikidata.json" respectively?

Thanks!

**Comment by mingdachen** [comment]
Hi @l11x0m7 , yes they are included in those json files.

**Comment by mingdachen** [comment]
I'm closing this issue as I just uploaded the code and the trained models. Let me know if you have any other questions.
